const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const assert = require('node:assert/strict');
const root=path.resolve(__dirname,'../../..');
const {chromium}=require(path.join(root,'frontend/node_modules/playwright'));
const out=process.env.AUDIT_BROWSER_OUTPUT||path.join(root,'reports/criteria-audit');
const currentPort=Number(process.env.AUDIT_BROWSER_PORT||8766);
const folder=path.join(out,'artifacts/browser-current');fs.mkdirSync(folder,{recursive:true});
const save=(name,value)=>fs.writeFileSync(path.join(out,'evidence',name),JSON.stringify(value,null,2));
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const features=[];
 for(const port of [8765,currentPort]){
  await page.goto(`http://127.0.0.1:${port}`);
  const r=await page.request.post(`http://127.0.0.1:${port}/api/auth/register`,{data:{username:'audit_'+crypto.randomBytes(5).toString('hex'),password:crypto.randomBytes(20).toString('hex'),position:'Criteria audit'}});
  assert.ok([200,201].includes(r.status()));
  await page.goto(`http://127.0.0.1:${port}/studio`);
  await page.locator('#generateButton').waitFor({state:'visible'});
  await page.waitForFunction(()=>!document.querySelector('#modelNote').textContent.includes('Проверяем'));
  features.push({port,version:port===8765?'existing dist':'fresh build from current sources',image_upload:await page.locator('#imageFiles').count(),purpose_selector:await page.locator('#purpose').count(),model_note:await page.locator('#modelNote').innerText()});
 }
 save('frontend-features.json',features);
 await page.locator('#generateButton').click();
 const noTemplate=await page.locator('#status').innerText();
 await page.locator('#templateFile').setInputFiles(path.join(root,'external-fixtures/expansion-20260922/templates/pptmaster-brutalism_field_guide.pptx'));
 await page.locator('#uploadButton').click();
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Шаблон готов'));
 const templateId=await page.locator('#template').inputValue();
 await page.reload();
 await page.waitForFunction(()=>document.querySelector('#template')?.options.length && document.querySelector('#template').value);
 const persisted=templateId===await page.locator('#template').inputValue();
 await page.locator('#content').fill('Краткий бриф: запустить пилот поиска по регламентам для 150 сотрудников на 6 недель.');
 await page.locator('#count').fill('10');
 await page.locator('#generateButton').click();
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Not enough'),{},{timeout:60000});
 const briefError=await page.locator('#status').innerText();
 await page.screenshot({path:path.join(folder,'brief-without-model.png')});
 await page.locator('#content').fill(fs.readFileSync(path.join(root,'examples/acceptance_content.md'),'utf8'));
 await page.locator('#imageFiles').setInputFiles(fs.readdirSync(path.join(root,'examples/acceptance_images')).filter(x=>x.endsWith('.png')).map(x=>path.join(root,'examples/acceptance_images',x)));
 await page.locator('#generateButton').click();
 await page.locator('#variants button').first().waitFor({timeout:120000});
 const generationStatus=await page.locator('#status').innerText();
 await page.screenshot({path:path.join(folder,'generated-deck.png'),fullPage:true});
 const download=page.waitForEvent('download');await page.locator('.downloads a').first().click();
 const downloaded=await download;await downloaded.saveAs(path.join(folder,'browser-download.pptx'));
 const batchId=await page.locator('#batches').inputValue();
 const batch=await (await page.request.get(`http://127.0.0.1:${currentPort}/v1/batches/${batchId}`)).json();
 save('browser-batch.json',batch);
 const first=page.locator('.audit-issue input[type=checkbox]').first();
 await first.check();
 const responsePromise=page.waitForResponse(r=>r.url().endsWith('/repair')&&r.request().method()==='POST',{timeout:120000});
 await page.getByRole('button',{name:/Исправить выбранные/}).click();
 const repairResponse=await responsePromise;
 const repair=await repairResponse.json();save('repair-response.json',repair);
 await page.waitForFunction(()=>!document.querySelector('#workspace').getAttribute('aria-busy')||document.querySelector('#workspace').getAttribute('aria-busy')==='false');
 await page.screenshot({path:path.join(folder,'after-selected-repair.png'),fullPage:true});
 const result={browser:await browser.version(),no_template:noTemplate,template_persisted:persisted,brief_error:briefError,generated_status:generationStatus,variants:batch.variants?.length,download_bytes:fs.statSync(path.join(folder,'browser-download.pptx')).size,repair_http:repairResponse.status(),repair_status:repair.status,revision:repair.revision,remaining_issues:repair.qa?.issues.length,page_errors:errors};
 save('browser-current.json',result);console.log(JSON.stringify(result));await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
