const $ = id => document.getElementById(id);
let decks = [], busy = false;
function node(tag, text, className) { const e = document.createElement(tag); if (text !== undefined) e.textContent = text; if(className) e.className = className; return e; }
function status(message, error=false) { $('status').textContent=message; $('status').className=error?'error':''; }
function setBusy(value) { busy=value; document.querySelectorAll('form button').forEach(b=>b.disabled=value); $('statusBadge').textContent=value?'В работе':'Готов к работе'; }
async function request(url, options) { const r=await fetch(url,options); const data=await r.json(); if(!r.ok) throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail)); return data; }
async function templates(selected) { const list=await request('/v1/templates'); $('template').replaceChildren(); for(const t of list){const o=node('option', t.source_file);o.value=t.template_id;$('template').append(o);} if(selected) $('template').value=selected; }
$('upload').addEventListener('submit', async e=>{ e.preventDefault(); if(busy)return;setBusy(true);status('Анализируем оформление и макеты шаблона…');try{const data=new FormData();data.append('file',$('templateFile').files[0]);data.append('offline',String($('offline').checked));const t=await request('/v1/templates/analyze',{method:'POST',body:data});await templates(t.template_id);status(`Шаблон готов: ${t.slide_count} слайдов, ${t.pattern_count} вариантов макета.`);}catch(err){status(err.message,true);}finally{setBusy(false);}});
$('generate').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;if(!$('template').value){status('Сначала добавьте шаблон.',true);return;}if(!$('content').value.trim()&&!$('contentFile').files.length){status('Добавьте текст или файл с материалами.',true);return;}setBusy(true);$('progress').hidden=false;$('progress').value=0;status('Создаём презентации…');try{const data=new FormData();data.append('template_id',$('template').value);data.append('content',$('content').value);data.append('slide_count',$('count').value);data.append('offline',String($('offline').checked));data.append('variants','true');data.append('export_all','true');if($('contentFile').files.length)data.append('content_file',$('contentFile').files[0]);const job=await request('/v1/presentations/jobs',{method:'POST',body:data});await poll(job.job_id);}catch(err){status(err.message,true);}finally{setBusy(false);$('progress').hidden=true;}});
async function poll(id){for(;;){const job=await request(`/v1/jobs/${id}`);$('progress').value=job.progress;const stage=job.stage.split(':').pop();const labels={template_analysis:'Разбираем шаблон',content_planning:'Планируем содержание',layout_mapping:'Выбираем макеты',composition:'Собираем слайды',quality_assurance:'Проверяем вёрстку',export:'Готовим PDF и HTML'};status((labels[stage]||'Обрабатываем материалы')+` · ${job.progress}%`);if(job.status==='completed'||job.status==='failed'){if(job.batch){decks=job.batch.variants;showTabs();await loadHistory();$('batches').value=job.batch.batch_id;status(job.status==='failed'?'Некоторые варианты требуют проверки. Результаты и замечания доступны ниже.':job.batch.diversity_status==='passed'?'Три варианта готовы. Выберите подходящий.':'Готово. В этом шаблоне недостаточно различающихся макетов — проверьте варианты.',job.status==='failed');return;}throw new Error(job.error||'Не удалось завершить генерацию');}await new Promise(r=>setTimeout(r,1200));}}
function showTabs(active=0){$('empty').hidden=true;$('variants').replaceChildren();decks.forEach((d,i)=>{const b=node('button',d.variant?.label||'Исправленная версия',i===active?'active':'');b.type='button';b.onclick=()=>showTabs(i);$('variants').append(b);});showDeck(decks[active]);}
function showDeck(deck){const container=$('deck');container.replaceChildren();const id=encodeURIComponent(deck.presentation_id);const qa=deck.qa;const downloads=node('div',undefined,'downloads');for(const format of ['pptx',...Object.keys(deck.exports?.artifacts||{})]){const a=node('a',format.toUpperCase());a.href=`/v1/presentations/${id}/download?format=${format}`;a.download='';downloads.append(a);}container.append(downloads);container.append(node('div',`Проверка вёрстки: ${qa.status==='failed'?'есть ошибки':qa.status==='warning'?'есть замечания':'пройдена'}. Замечаний: ${qa.issues.filter(i=>i.severity!=='info').length}. Смысловая проверка моделью не проводилась. ${['offline','fallback'].includes(deck.planner_mode)?'Содержание распределено без LLM.':''}`, 'qa-note'));
for(const issue of deck.exports?.issues||[])container.append(node('p',issue.message,'qa-note'));
const selected=new Set();const repair=node('button','Исправить выбранные замечания','repair');repair.disabled=true;repair.onclick=async()=>{if(busy)return;setBusy(true);repair.disabled=true;status('Пересобираем выбранные слайды в новой версии…');try{const fixed=await request(`/v1/presentations/${id}/repair`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({issue_ids:[...selected]})});decks.push(fixed);showTabs(decks.length-1);status('Новая версия готова. Проверьте оставшиеся замечания.');}catch(err){status(err.message,true);}finally{setBusy(false);repair.disabled=selected.size===0;}};
for(let n=1;n<=deck.slide_count;n++){const card=node('article',undefined,'slide-card');card.append(node('div',`Слайд ${String(n).padStart(2,'0')}`,'slide-head'));const view=node('div',undefined,'slide-view');if(deck.exports?.previews?.some(p=>p.slide===n)){const img=node('img');img.src=`/v1/presentations/${id}/preview/${n}`;img.alt=`Слайд ${n}`;img.loading='lazy';view.append(img);}else{view.append(node('p','Предпросмотр недоступен. Скачайте PPTX.'));}card.append(view);const issues=qa.issues.filter(i=>i.slide===n&&i.severity!=='info');const list=node('div',undefined,'issues');for(const issue of issues){const label=node('label',undefined,`issue ${issue.severity}`);if(issue.repairable){const check=node('input');check.type='checkbox';check.onchange=()=>{check.checked?selected.add(issue.id):selected.delete(issue.id);repair.disabled=selected.size===0;};label.append(check);}label.append(node('span',issue.message));list.append(label);for(const b of issue.bounds||[]){const mark=node('div',undefined,'mark');Object.assign(mark.style,{left:`${100*b.x/qa.canvas.width_inches}%`,top:`${100*b.y/qa.canvas.height_inches}%`,width:`${100*b.w/qa.canvas.width_inches}%`,height:`${100*b.h/qa.canvas.height_inches}%`});view.append(mark);}}card.append(list);container.append(card);}
for(const issue of qa.issues.filter(i=>!i.slide&&i.severity!=='info'))container.append(node('p',issue.message,'qa-note'));if(qa.issues.some(i=>i.repairable&&i.slide&&i.severity!=='info'))container.append(repair);}
async function loadHistory(){const list=await request('/v1/batches');$('history').hidden=!list.length;const select=$('batches');select.replaceChildren(node('option','Выберите результат'));select.firstChild.value='';for(const batch of list){const template=[...$('template').options].find(o=>o.value===batch.template_id)?.textContent||batch.template_id;const option=node('option',template+' · '+batch.batch_id.slice(-17));option.value=batch.batch_id;select.append(option);}}
$('batches').onchange=async()=>{if(!$('batches').value||busy)return;try{const batch=await request('/v1/batches/'+encodeURIComponent($('batches').value));decks=batch.variants;showTabs();status('Загружен сохранённый результат.');}catch(e){status(e.message,true);}};
templates().then(loadHistory).catch(e=>status(e.message,true));
